development:
  host: localhost
  uid_field: eppn
  extra_fields:
    - eppn
    - unscoped-affiliation
    - uid
    - sn
    - nickname
    - givenName
  request_type: header
  info_fields:
    name: displayName
    email: mail

test:
  host: localhost
  uid_field: eppn
  extra_fields:
    - eppn
    - unscoped-affiliation
    - uid
    - sn
    - nickname
    - givenName
  request_type: header
  info_fields:
    name: displayName
    email: mail

demo:
  host: demo.ideals.illinois.edu
  uid_field: eppn
  extra_fields:
    - eppn
    - unscoped-affiliation
    - uid
    - sn
    - nickname
    - givenName
  request_type: header
  info_fields:
    name: displayName
    email: mail

production:
  host: ideals.illinois.edu
  uid_field: eppn
  extra_fields:
    - eppn
    - unscoped-affiliation
    - uid
    - sn
    - nickname
    - givenName
  request_type: header
  info_fields:
    name: displayName
    email: mail
